name: Run repository search

on:
  # schedule:
  #   # Runs at 00:00 UTC every day
  #   - cron: '0 19 * * *'
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have a requirements.txt file:
        pip install -r requirements.txt
        
    - name: Run script
      run: python query_moj_frontend.py
      # If your script needs environment variables:
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
